# Generated by Django 6.1.1 on 2026-09-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=120)),
                ('responsable', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
